--------------------------------------------------------
-- Archivo creado  - miércoles-setiembre-03-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CICLISTA
--------------------------------------------------------

  CREATE TABLE "ANDRE"."CICLISTA" 
   (	"ID" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"NACIONALIDAD" VARCHAR2(100 BYTE), 
	"FECHA_NACIMIENTO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD" ;
--------------------------------------------------------
--  DDL for Table CONTRATO
--------------------------------------------------------

  CREATE TABLE "ANDRE"."CONTRATO" 
   (	"ID" NUMBER(10,0), 
	"ID_CICLISTA" NUMBER(10,0), 
	"ID_EQUIPO" NUMBER(10,0), 
	"FECHA_INICIO" DATE, 
	"FECHA_FIN" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD" ;
--------------------------------------------------------
--  DDL for Table EQUIPO
--------------------------------------------------------

  CREATE TABLE "ANDRE"."EQUIPO" 
   (	"ID" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"NACIONALIDAD" VARCHAR2(100 BYTE), 
	"NOMBRE_DIRECTOR" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD" ;
--------------------------------------------------------
--  DDL for Table PARTICIPACION
--------------------------------------------------------

  CREATE TABLE "ANDRE"."PARTICIPACION" 
   (	"ID_EQUIPO" NUMBER(10,0), 
	"ID_PRUEBA" NUMBER(10,0), 
	"PUESTO_FINAL" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD" ;
--------------------------------------------------------
--  DDL for Table PRUEBA
--------------------------------------------------------

  CREATE TABLE "ANDRE"."PRUEBA" 
   (	"ID" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"ANO_EDICION" NUMBER(4,0), 
	"NUM_ETAPAS" NUMBER(4,0), 
	"KM_TOTALES" NUMBER(8,2), 
	"GANADOR_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD" ;
--------------------------------------------------------
--  DDL for Index IX_CONTRATO_CICLISTA
--------------------------------------------------------

  CREATE INDEX "ANDRE"."IX_CONTRATO_CICLISTA" ON "ANDRE"."CONTRATO" ("ID_CICLISTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD" ;
--------------------------------------------------------
--  DDL for Index IX_CONTRATO_EQUIPO
--------------------------------------------------------

  CREATE INDEX "ANDRE"."IX_CONTRATO_EQUIPO" ON "ANDRE"."CONTRATO" ("ID_EQUIPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD" ;
--------------------------------------------------------
--  DDL for Index IX_PARTICIPACION_EQUIPO
--------------------------------------------------------

  CREATE INDEX "ANDRE"."IX_PARTICIPACION_EQUIPO" ON "ANDRE"."PARTICIPACION" ("ID_EQUIPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD" ;
--------------------------------------------------------
--  DDL for Index IX_PARTICIPACION_PRUEBA
--------------------------------------------------------

  CREATE INDEX "ANDRE"."IX_PARTICIPACION_PRUEBA" ON "ANDRE"."PARTICIPACION" ("ID_PRUEBA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD" ;
--------------------------------------------------------
--  DDL for Index IX_PRUEBA_GANADOR
--------------------------------------------------------

  CREATE INDEX "ANDRE"."IX_PRUEBA_GANADOR" ON "ANDRE"."PRUEBA" ("GANADOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD" ;
--------------------------------------------------------
--  DDL for Index PK_CICLISTA
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANDRE"."PK_CICLISTA" ON "ANDRE"."CICLISTA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD" ;
--------------------------------------------------------
--  DDL for Index PK_CONTRATO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANDRE"."PK_CONTRATO" ON "ANDRE"."CONTRATO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD" ;
--------------------------------------------------------
--  DDL for Index PK_EQUIPO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANDRE"."PK_EQUIPO" ON "ANDRE"."EQUIPO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD" ;
--------------------------------------------------------
--  DDL for Index PK_PARTICIPACION
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANDRE"."PK_PARTICIPACION" ON "ANDRE"."PARTICIPACION" ("ID_EQUIPO", "ID_PRUEBA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD" ;
--------------------------------------------------------
--  DDL for Index PK_PRUEBA
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANDRE"."PK_PRUEBA" ON "ANDRE"."PRUEBA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD" ;
--------------------------------------------------------
--  DDL for Index PK_CICLISTA
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANDRE"."PK_CICLISTA" ON "ANDRE"."CICLISTA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD" ;
--------------------------------------------------------
--  DDL for Index PK_CONTRATO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANDRE"."PK_CONTRATO" ON "ANDRE"."CONTRATO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD" ;
--------------------------------------------------------
--  DDL for Index IX_CONTRATO_CICLISTA
--------------------------------------------------------

  CREATE INDEX "ANDRE"."IX_CONTRATO_CICLISTA" ON "ANDRE"."CONTRATO" ("ID_CICLISTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD" ;
--------------------------------------------------------
--  DDL for Index IX_CONTRATO_EQUIPO
--------------------------------------------------------

  CREATE INDEX "ANDRE"."IX_CONTRATO_EQUIPO" ON "ANDRE"."CONTRATO" ("ID_EQUIPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD" ;
--------------------------------------------------------
--  DDL for Index PK_EQUIPO
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANDRE"."PK_EQUIPO" ON "ANDRE"."EQUIPO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD" ;
--------------------------------------------------------
--  DDL for Index IX_PARTICIPACION_EQUIPO
--------------------------------------------------------

  CREATE INDEX "ANDRE"."IX_PARTICIPACION_EQUIPO" ON "ANDRE"."PARTICIPACION" ("ID_EQUIPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD" ;
--------------------------------------------------------
--  DDL for Index IX_PARTICIPACION_PRUEBA
--------------------------------------------------------

  CREATE INDEX "ANDRE"."IX_PARTICIPACION_PRUEBA" ON "ANDRE"."PARTICIPACION" ("ID_PRUEBA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD" ;
--------------------------------------------------------
--  DDL for Index PK_PARTICIPACION
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANDRE"."PK_PARTICIPACION" ON "ANDRE"."PARTICIPACION" ("ID_EQUIPO", "ID_PRUEBA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD" ;
--------------------------------------------------------
--  DDL for Index IX_PRUEBA_GANADOR
--------------------------------------------------------

  CREATE INDEX "ANDRE"."IX_PRUEBA_GANADOR" ON "ANDRE"."PRUEBA" ("GANADOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD" ;
--------------------------------------------------------
--  DDL for Index PK_PRUEBA
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANDRE"."PK_PRUEBA" ON "ANDRE"."PRUEBA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD" ;
--------------------------------------------------------
--  Constraints for Table CICLISTA
--------------------------------------------------------

  ALTER TABLE "ANDRE"."CICLISTA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ANDRE"."CICLISTA" MODIFY ("NACIONALIDAD" NOT NULL ENABLE);
  ALTER TABLE "ANDRE"."CICLISTA" MODIFY ("FECHA_NACIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "ANDRE"."CICLISTA" ADD CONSTRAINT "PK_CICLISTA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTRATO
--------------------------------------------------------

  ALTER TABLE "ANDRE"."CONTRATO" MODIFY ("FECHA_INICIO" NOT NULL ENABLE);
  ALTER TABLE "ANDRE"."CONTRATO" MODIFY ("FECHA_FIN" NOT NULL ENABLE);
  ALTER TABLE "ANDRE"."CONTRATO" ADD CONSTRAINT "PK_CONTRATO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EQUIPO
--------------------------------------------------------

  ALTER TABLE "ANDRE"."EQUIPO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ANDRE"."EQUIPO" MODIFY ("NACIONALIDAD" NOT NULL ENABLE);
  ALTER TABLE "ANDRE"."EQUIPO" MODIFY ("NOMBRE_DIRECTOR" NOT NULL ENABLE);
  ALTER TABLE "ANDRE"."EQUIPO" ADD CONSTRAINT "PK_EQUIPO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PARTICIPACION
--------------------------------------------------------

  ALTER TABLE "ANDRE"."PARTICIPACION" MODIFY ("ID_EQUIPO" NOT NULL ENABLE);
  ALTER TABLE "ANDRE"."PARTICIPACION" MODIFY ("ID_PRUEBA" NOT NULL ENABLE);
  ALTER TABLE "ANDRE"."PARTICIPACION" MODIFY ("PUESTO_FINAL" NOT NULL ENABLE);
  ALTER TABLE "ANDRE"."PARTICIPACION" ADD CONSTRAINT "CK_PARTICIPACION_PUESTO" CHECK (puesto_final >= 1) ENABLE;
  ALTER TABLE "ANDRE"."PARTICIPACION" ADD CONSTRAINT "PK_PARTICIPACION" PRIMARY KEY ("ID_EQUIPO", "ID_PRUEBA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRUEBA
--------------------------------------------------------

  ALTER TABLE "ANDRE"."PRUEBA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ANDRE"."PRUEBA" MODIFY ("ANO_EDICION" NOT NULL ENABLE);
  ALTER TABLE "ANDRE"."PRUEBA" MODIFY ("NUM_ETAPAS" NOT NULL ENABLE);
  ALTER TABLE "ANDRE"."PRUEBA" MODIFY ("KM_TOTALES" NOT NULL ENABLE);
  ALTER TABLE "ANDRE"."PRUEBA" ADD CONSTRAINT "PK_PRUEBA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTRATO
--------------------------------------------------------

  ALTER TABLE "ANDRE"."CONTRATO" ADD CONSTRAINT "FK_CONTRATO_CICLISTA" FOREIGN KEY ("ID_CICLISTA")
	  REFERENCES "ANDRE"."CICLISTA" ("ID") ENABLE;
  ALTER TABLE "ANDRE"."CONTRATO" ADD CONSTRAINT "FK_CONTRATO_EQUIPO" FOREIGN KEY ("ID_EQUIPO")
	  REFERENCES "ANDRE"."EQUIPO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARTICIPACION
--------------------------------------------------------

  ALTER TABLE "ANDRE"."PARTICIPACION" ADD CONSTRAINT "FK_PARTICIPACION_EQUIPO" FOREIGN KEY ("ID_EQUIPO")
	  REFERENCES "ANDRE"."EQUIPO" ("ID") ENABLE;
  ALTER TABLE "ANDRE"."PARTICIPACION" ADD CONSTRAINT "FK_PARTICIPACION_PRUEBA" FOREIGN KEY ("ID_PRUEBA")
	  REFERENCES "ANDRE"."PRUEBA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRUEBA
--------------------------------------------------------

  ALTER TABLE "ANDRE"."PRUEBA" ADD CONSTRAINT "FK_PRUEBA_GANADOR" FOREIGN KEY ("GANADOR_ID")
	  REFERENCES "ANDRE"."CICLISTA" ("ID") ENABLE;
